# Generated by Django 2.1.7 on 2019-02-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Только буквы, цифры и @ /. / + / - / _. ', max_length=128, unique=True, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('photo', models.ImageField(blank=True, default='photos/unknown_user.jpg', upload_to='photos/%Y_%m/%d', verbose_name='Фото')),
                ('status', models.CharField(max_length=32, verbose_name='Статус')),
                ('account', models.DecimalField(blank=True, decimal_places=2, default=100.0, max_digits=10, verbose_name='Счет')),
            ],
            options={
                'verbose_name': 'Посетитель',
                'verbose_name_plural': 'Посетители',
                'ordering': ['name'],
            },
        ),
        migrations.AlterIndexTogether(
            name='profile',
            index_together={('id', 'name', 'account')},
        ),
    ]
