# Generated by Django 2.1.7 on 2019-02-26 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(blank=True, default='0000000', on_delete=django.db.models.deletion.CASCADE, to='users.Profile', verbose_name='Владелец'),
        ),
    ]
